/**
 * lease / lib/render.mjs — the Tier-0 projection: an occupancy snapshot on disk.
 *
 * Written by a scheduled job (see PROCESS.md "Scheduling") next to whatever other projections
 * the company generates, and committed by that job's bot. Sessions and humans then read current
 * occupancy at a cost of ZERO API calls, which is what makes this scale past a handful of
 * sessions.
 *
 * It is a SNAPSHOT and says so in bold at the top. Acting on it without confirming via
 * `lease.mjs check` is the stale-data failure in a new costume, so the file states that itself
 * rather than leaving it to be learned the expensive way.
 *
 * Output must be IDEMPOTENT when the lease set has not changed, or the bot commits noise over
 * real history every day and people stop reading the file. The generation timestamp is the only
 * volatile field; `lease.mjs render --out` strips it before comparing.
 */
import { isLive, isExpired } from './claims.mjs';

const hhmm = (iso) => (iso ? String(iso).slice(11, 16) : '--:--');
const ymd = (iso) => (iso ? String(iso).slice(0, 10) : '-');

function ageHours(fromIso, nowMs) {
  const t = Date.parse(fromIso ?? '');
  if (Number.isNaN(t)) return null;
  return (nowMs - t) / 3600000;
}

export function renderProjection(claims, { nowMs, cfg, ledger }) {
  const live = claims.filter((c) => isLive(c.rec, nowMs)).sort((a, b) => a.rec.key.localeCompare(b.rec.key));
  const terminal = claims.filter((c) => !isLive(c.rec, nowMs));

  const L = [];
  L.push('# Occupancy: live leases');
  L.push('');
  L.push(`**Snapshot at ${new Date(nowMs).toISOString().slice(0, 16).replace('T', ' ')} UTC. Not grounds for action.**`);
  L.push('Before writing to any shared area, confirm. It costs one call:');
  L.push('');
  L.push('```');
  L.push('node .claude/skills/lease/lease.mjs check --key "<key>"');
  L.push('```');
  L.push('');
  L.push('Acting on this file without confirming is the same class of mistake as working from a');
  L.push('stale clone: the snapshot describes the past, and you are writing in the present.');
  L.push('Generated by `lease.mjs render` — do not edit by hand.');
  L.push('');
  L.push(`Ledger: ${ledger.repo}#${ledger.issue ?? '-'} · index label: \`${cfg.index_label ?? '-'}\` · enforcement: \`${JSON.stringify(cfg.enforce)}\``);
  L.push('');

  L.push('## Live leases');
  L.push('');
  if (!live.length) {
    L.push('_No live leases._');
  } else {
    L.push('| Key | Holder | Host / runtime | Taken | Until | behind | Scope | Intent |');
    L.push('|---|---|---|---|---|---|---|---|');
    for (const c of live) {
      const r = c.rec, h = r.holder ?? {}, cl = r.clone ?? {}, t = r.t ?? {};
      L.push(`| \`${r.key}\` | ${h.login ?? '?'} | ${h.host ?? '?'} / ${h.runtime ?? '?'} | ${hhmm(t.acquired)} | ${hhmm(t.expires)} | ${cl.behind ?? '?'} | ${(r.scope ?? []).join('<br>') || '-'} | ${r.intent || '-'} |`);
    }
  }
  L.push('');

  // Everything below is what a human must look at. An empty section here is the good outcome.
  const susp = [];
  for (const c of live) {
    const r = c.rec;
    if ((r.clone?.behind ?? 0) > 0) {
      susp.push(`\`${r.key}\` — holder is on a stale clone (**behind ${r.clone.behind}**), ${r.holder?.login}@${r.holder?.host}. Its writes may bury newer work.`);
    }
    const ah = ageHours(r.t?.acquired, nowMs);
    if (ah !== null && ah > 4) {
      susp.push(`\`${r.key}\` — held for **${ah.toFixed(1)}h** by ${r.holder?.login}@${r.holder?.host}. Live work, or a forgotten process?`);
    }
    if (Math.abs(r.t?.skew_s ?? 0) > (cfg.clock_skew_warn_s ?? 120)) {
      susp.push(`\`${r.key}\` — holder's clock differs from GitHub by ${r.t.skew_s}s.`);
    }
  }
  for (const c of terminal) {
    const r = c.rec;
    if (r.state === 'held' && isExpired(r, nowMs)) {
      susp.push(`\`${r.key}\` — **expired and not yet reaped** (lapsed ${hhmm(r.t?.expires)}, ${ymd(r.t?.expires)}). Free for anyone to take.`);
    }
    if (r.state === 'stolen') susp.push(`\`${r.key}\` — **stolen**: ${r.reason || 'no reason given'} (from ${r.holder?.login}@${r.holder?.host}).`);
    if (r.state === 'yielded') susp.push(`\`${r.key}\` — yielded: ${r.reason || 'no reason given'}.`);
  }

  L.push('## Expired / suspicious');
  L.push('');
  L.push(susp.length ? susp.map((s) => `- ${s}`).join('\n') : '_Clean._');
  L.push('');

  L.push('## How to read this');
  L.push('');
  L.push('- `issue:<owner>/<repo>#<N>` — a task. `path:<glob>` — an area of files. `process:<name>` — a run. `branch:<name>` — a branch.');
  L.push('- `behind` — how many commits the holder\'s clone was behind when it took the lease. For `path:`/`branch:` keys this must be zero.');
  L.push('- A lease expires on its own. Reaping only tidies the record; correctness does not depend on it.');
  L.push('- Rules and exceptions: see the concurrency policy referenced from `.claude/skills/lease/SKILL.md`.');
  L.push('');

  // Machine-readable tail: scripts read THIS, never the markdown above.
  const payload = {
    generated_at: new Date(nowMs).toISOString(),
    ledger,
    enforce: cfg.enforce,
    leases: live.map((c) => ({ comment_id: c.id, ...c.rec })),
  };
  L.push(`<!-- opos-leases:v1 ${JSON.stringify(payload)} -->`);
  L.push('');
  return L.join('\n');
}

/** One line for the SessionStart greeting. Parses the tail, never the markdown. */
export function summarizeProjection(text, { cloneId } = {}) {
  if (!text) return null;
  const i = text.indexOf('<!-- opos-leases:v1 ');
  if (i === -1) return null;
  const j = text.indexOf(' -->', i);
  if (j === -1) return null;
  try {
    const p = JSON.parse(text.slice(i + '<!-- opos-leases:v1 '.length, j));
    const mine = (p.leases ?? []).filter((l) => l.holder?.clone_id === cloneId);
    const others = (p.leases ?? []).filter((l) => l.holder?.clone_id !== cloneId);
    return { generated_at: p.generated_at, mine, others, total: (p.leases ?? []).length };
  } catch { return null; }
}
